name: mic_stream_plus
description: The mic_stream_plus plugin
version: 0.0.1
author: Neohelden GmbH
homepage: https://neohelden.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Manages os permissions for microphone and storage access.
  permission_handler: ^6.0.1+1

  # OS information
  os_detect: ^2.0.0-nullsafety.0

  # Join paths.
  path: ^1.8.0

  # Cross platform files
  cross_file: ^0.3.1

dev_dependencies:
  # Enforces effective dart code style.
  effective_dart: ^1.3.1

  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.neohelden.mic_stream_plus
        pluginClass: MicStreamPlusPlugin
      ios:
        pluginClass: MicStreamPlusPlugin
      macos:
        pluginClass: MicStreamPlusPlugin
